"""scholarship source url and deadline note

Revision ID: 500b4e3ef347
Revises: 62cbf9a1dbbc
Create Date: 2026-09-05 15:59:16.635578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '500b4e3ef347'
down_revision: Union[str, Sequence[str], None] = '62cbf9a1dbbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scholarships', schema=None) as batch_op:
        # server_default is required: adding a NOT NULL column to a table that
        # already has rows fails without one.
        batch_op.add_column(sa.Column('deadline_note', sa.String(length=255),
                                      nullable=False, server_default=''))
        batch_op.add_column(sa.Column('source_url', sa.String(length=500),
                                      nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scholarships', schema=None) as batch_op:
        batch_op.drop_column('source_url')
        batch_op.drop_column('deadline_note')

    # ### end Alembic commands ###
