"""requirements provenance columns

Revision ID: 62cbf9a1dbbc
Revises: 8dfcfb664ca7
Create Date: 2026-09-05 15:53:20.928401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62cbf9a1dbbc'
down_revision: Union[str, Sequence[str], None] = '8dfcfb664ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirements_source', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('requirements_verified', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_universities_ipeds_unitid'), ['ipeds_unitid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_universities_ipeds_unitid'))
        batch_op.drop_column('requirements_verified')
        batch_op.drop_column('requirements_source')

    # ### end Alembic commands ###
