"""initial schema

Revision ID: 8dfcfb664ca7
Revises: 
Create Date: 2026-09-05 15:44:11.442608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dfcfb664ca7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('amount_max', sa.Integer(), nullable=True),
    sa.Column('renewable', sa.Boolean(), nullable=False),
    sa.Column('eligibility', sa.String(length=20), nullable=False),
    sa.Column('min_gpa', sa.Float(), nullable=True),
    sa.Column('majors', sa.JSON(), nullable=False),
    sa.Column('deadline', sa.String(length=5), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('data_source', sa.String(length=255), nullable=False),
    sa.Column('last_verified', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipeds_unitid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('control', sa.String(length=10), nullable=False),
    sa.Column('undergrad_enrollment', sa.Integer(), nullable=True),
    sa.Column('intl_student_share', sa.Float(), nullable=True),
    sa.Column('acceptance_rate', sa.Float(), nullable=True),
    sa.Column('sat_25', sa.Integer(), nullable=True),
    sa.Column('sat_75', sa.Integer(), nullable=True),
    sa.Column('act_25', sa.Integer(), nullable=True),
    sa.Column('act_75', sa.Integer(), nullable=True),
    sa.Column('test_policy', sa.String(length=20), nullable=False),
    sa.Column('tuition_in_state', sa.Integer(), nullable=True),
    sa.Column('tuition_out_state', sa.Integer(), nullable=True),
    sa.Column('cost_of_attendance', sa.Integer(), nullable=True),
    sa.Column('toefl_min', sa.Integer(), nullable=True),
    sa.Column('ielts_min', sa.Float(), nullable=True),
    sa.Column('offers_intl_aid', sa.Boolean(), nullable=False),
    sa.Column('intl_support_notes', sa.Text(), nullable=False),
    sa.Column('app_platforms', sa.JSON(), nullable=False),
    sa.Column('majors', sa.JSON(), nullable=False),
    sa.Column('deadlines', sa.JSON(), nullable=False),
    sa.Column('supplemental_essay_count', sa.Integer(), nullable=False),
    sa.Column('application_fee', sa.Integer(), nullable=True),
    sa.Column('links', sa.JSON(), nullable=False),
    sa.Column('data_source', sa.String(length=255), nullable=False),
    sa.Column('last_verified', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_universities_ipeds_unitid'), ['ipeds_unitid'], unique=True)
        batch_op.create_index(batch_op.f('ix_universities_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_universities_state'), ['state'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'university_id', name='uq_user_university')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=100), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='uq_user_dedupe')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('student_type', sa.String(length=20), nullable=False),
    sa.Column('applicant_level', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('gpa_scale', sa.Float(), nullable=False),
    sa.Column('sat', sa.Integer(), nullable=True),
    sa.Column('act', sa.Integer(), nullable=True),
    sa.Column('toefl', sa.Integer(), nullable=True),
    sa.Column('ielts', sa.Float(), nullable=True),
    sa.Column('intended_major', sa.String(length=100), nullable=True),
    sa.Column('financial_aid_needed', sa.Boolean(), nullable=False),
    sa.Column('courses', sa.JSON(), nullable=False),
    sa.Column('activities', sa.JSON(), nullable=False),
    sa.Column('awards', sa.JSON(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tutor_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tutor_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tutor_messages_user_id'), ['user_id'], unique=False)

    op.create_table('essays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('essay_type', sa.String(length=30), nullable=False),
    sa.Column('word_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('essays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_essays_user_id'), ['user_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('auto_generated', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('essay_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('essay_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['essay_id'], ['essays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('essay_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_essay_drafts_essay_id'), ['essay_id'], unique=False)

    op.create_table('essay_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('paragraph_feedback', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['essay_drafts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('essay_feedback')
    with op.batch_alter_table('essay_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_essay_drafts_essay_id'))

    op.drop_table('essay_drafts')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_application_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('essays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_essays_user_id'))

    op.drop_table('essays')
    with op.batch_alter_table('tutor_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tutor_messages_user_id'))

    op.drop_table('tutor_messages')
    op.drop_table('student_profiles')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_user_id'))

    op.drop_table('applications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_universities_state'))
        batch_op.drop_index(batch_op.f('ix_universities_name'))
        batch_op.drop_index(batch_op.f('ix_universities_ipeds_unitid'))

    op.drop_table('universities')
    op.drop_table('scholarships')
    # ### end Alembic commands ###
