"""Sample university seed data.

IMPORTANT: every number here is illustrative, approximate, and UNVERIFIED
(last_verified is intentionally null). It exists so the app works end-to-end
before real data ingestion (College Scorecard API / IPEDS) is wired up in a
later phase. The UI must always show data_source and last_verified.
"""

from sqlalchemy.orm import Session

from .models import University

CS = "computer_science"
ENG = "engineering"
BIO = "biology"
BUS = "business"
PSY = "psychology"
MATH = "mathematics"
ECON = "economics"
NURS = "nursing"

SAMPLE_UNIVERSITIES = [
    dict(name="Massachusetts Institute of Technology", city="Cambridge", state="MA", control="private",
         undergrad_enrollment=4600, acceptance_rate=0.045, sat_25=1520, sat_75=1580, act_25=34, act_75=36,
         test_policy="required", tuition_out_state=61990, cost_of_attendance=85000, toefl_min=90, ielts_min=7.0,
         offers_intl_aid=True, intl_support_notes="Need-blind for all applicants including international.",
         app_platforms=["institutional"], majors=[CS, ENG, MATH, BIO, ECON],
         deadlines={"early_action": "11-01", "regular": "01-06"}, supplemental_essay_count=5, application_fee=75),
    dict(name="Stanford University", city="Stanford", state="CA", control="private",
         undergrad_enrollment=7800, acceptance_rate=0.04, sat_25=1500, sat_75=1570, act_25=33, act_75=35,
         test_policy="required", tuition_out_state=62484, cost_of_attendance=87000, toefl_min=100, ielts_min=7.0,
         offers_intl_aid=True, intl_support_notes="Meets full need; need-aware for international applicants.",
         app_platforms=["common_app"], majors=[CS, ENG, BIO, ECON, PSY],
         deadlines={"early_action": "11-01", "regular": "01-05"}, supplemental_essay_count=3, application_fee=90),
    dict(name="Harvard University", city="Cambridge", state="MA", control="private",
         undergrad_enrollment=7100, acceptance_rate=0.035, sat_25=1490, sat_75=1580, act_25=34, act_75=36,
         test_policy="required", tuition_out_state=59320, cost_of_attendance=84000, toefl_min=100, ielts_min=7.0,
         offers_intl_aid=True, intl_support_notes="Need-blind and meets full need for all, including international.",
         app_platforms=["common_app"], majors=[CS, ECON, BIO, MATH, PSY],
         deadlines={"early_action": "11-01", "regular": "01-01"}, supplemental_essay_count=5, application_fee=85),
    dict(name="University of California, Berkeley", city="Berkeley", state="CA", control="public",
         undergrad_enrollment=32800, acceptance_rate=0.11, sat_25=None, sat_75=None, act_25=None, act_75=None,
         test_policy="blind", tuition_in_state=14850, tuition_out_state=48465, cost_of_attendance=75000,
         toefl_min=80, ielts_min=6.5, offers_intl_aid=False,
         intl_support_notes="Very limited aid for international students; strong international community.",
         app_platforms=["uc_application"], majors=[CS, ENG, ECON, BIO, PSY],
         deadlines={"regular": "11-30"}, supplemental_essay_count=4, application_fee=80),
    dict(name="University of California, Los Angeles", city="Los Angeles", state="CA", control="public",
         undergrad_enrollment=33000, acceptance_rate=0.09, test_policy="blind",
         tuition_in_state=13752, tuition_out_state=46326, cost_of_attendance=74000, toefl_min=83, ielts_min=6.5,
         offers_intl_aid=False, intl_support_notes="Dashew Center supports international students.",
         app_platforms=["uc_application"], majors=[CS, BIO, PSY, ECON, MATH],
         deadlines={"regular": "11-30"}, supplemental_essay_count=4, application_fee=80),
    dict(name="University of Michigan", city="Ann Arbor", state="MI", control="public",
         undergrad_enrollment=33700, acceptance_rate=0.18, sat_25=1350, sat_75=1530, act_25=31, act_75=34,
         test_policy="optional", tuition_in_state=17736, tuition_out_state=58072, cost_of_attendance=78000,
         toefl_min=88, ielts_min=6.5, offers_intl_aid=False,
         intl_support_notes="Large international population; little need-based intl aid.",
         app_platforms=["common_app"], majors=[CS, ENG, BUS, PSY, ECON],
         deadlines={"early_action": "11-01", "regular": "02-01", "transfer": "02-01"},
         supplemental_essay_count=2, application_fee=75),
    dict(name="Georgia Institute of Technology", city="Atlanta", state="GA", control="public",
         undergrad_enrollment=18500, acceptance_rate=0.16, sat_25=1370, sat_75=1530, act_25=31, act_75=35,
         test_policy="required", tuition_in_state=11764, tuition_out_state=32876, cost_of_attendance=55000,
         toefl_min=90, ielts_min=7.0, offers_intl_aid=False,
         intl_support_notes="Strong co-op program; popular with international STEM applicants.",
         app_platforms=["common_app"], majors=[CS, ENG, MATH, BUS],
         deadlines={"early_action": "10-16", "regular": "01-06", "transfer": "03-01"},
         supplemental_essay_count=1, application_fee=75),
    dict(name="University of Texas at Austin", city="Austin", state="TX", control="public",
         undergrad_enrollment=42400, acceptance_rate=0.29, sat_25=1230, sat_75=1480, act_25=26, act_75=33,
         test_policy="required", tuition_in_state=11698, tuition_out_state=41070, cost_of_attendance=62000,
         toefl_min=79, ielts_min=6.5, offers_intl_aid=False,
         intl_support_notes="Auto-admit rules apply to Texas residents; CS is far more competitive than average.",
         app_platforms=["applytexas", "common_app"], majors=[CS, ENG, BUS, BIO, ECON],
         deadlines={"early_action": "11-01", "regular": "12-01", "transfer": "03-01"},
         supplemental_essay_count=2, application_fee=75),
    dict(name="University of Illinois Urbana-Champaign", city="Champaign", state="IL", control="public",
         undergrad_enrollment=35000, acceptance_rate=0.44, sat_25=1340, sat_75=1510, act_25=29, act_75=34,
         test_policy="optional", tuition_in_state=17138, tuition_out_state=36068, cost_of_attendance=60000,
         toefl_min=79, ielts_min=6.5, offers_intl_aid=False,
         intl_support_notes="Top CS program with much lower admit rate than the university overall.",
         app_platforms=["institutional", "common_app"], majors=[CS, ENG, BUS, PSY],
         deadlines={"early_action": "11-01", "regular": "01-05", "transfer": "03-01"},
         supplemental_essay_count=2, application_fee=50),
    dict(name="Purdue University", city="West Lafayette", state="IN", control="public",
         undergrad_enrollment=39000, acceptance_rate=0.50, sat_25=1210, sat_75=1450, act_25=27, act_75=33,
         test_policy="required", tuition_in_state=9992, tuition_out_state=28794, cost_of_attendance=48000,
         toefl_min=80, ielts_min=6.5, offers_intl_aid=False,
         intl_support_notes="Tuition freeze for over a decade; very large international enrollment.",
         app_platforms=["common_app"], majors=[CS, ENG, BUS, BIO],
         deadlines={"early_action": "11-01", "regular": "01-15", "transfer": "03-01"},
         supplemental_essay_count=1, application_fee=60),
    dict(name="University of Washington", city="Seattle", state="WA", control="public",
         undergrad_enrollment=36000, acceptance_rate=0.43, test_policy="optional",
         tuition_in_state=12643, tuition_out_state=41997, cost_of_attendance=64000, toefl_min=76, ielts_min=6.0,
         offers_intl_aid=False, intl_support_notes="Direct-to-major CS admission is highly competitive.",
         app_platforms=["institutional"], majors=[CS, ENG, BIO, PSY, NURS],
         deadlines={"regular": "11-15", "transfer": "02-15"}, supplemental_essay_count=2, application_fee=80),
    dict(name="Carnegie Mellon University", city="Pittsburgh", state="PA", control="private",
         undergrad_enrollment=7500, acceptance_rate=0.11, sat_25=1500, sat_75=1560, act_25=34, act_75=35,
         test_policy="optional", tuition_out_state=63829, cost_of_attendance=84000, toefl_min=102, ielts_min=7.5,
         offers_intl_aid=False, intl_support_notes="SCS (computer science) admit rate is in the low single digits.",
         app_platforms=["common_app"], majors=[CS, ENG, BUS, MATH],
         deadlines={"early_decision": "11-01", "regular": "01-02", "transfer": "02-15"},
         supplemental_essay_count=3, application_fee=75),
    dict(name="Cornell University", city="Ithaca", state="NY", control="private",
         undergrad_enrollment=15700, acceptance_rate=0.07, sat_25=1470, sat_75=1550, act_25=33, act_75=35,
         test_policy="optional", tuition_out_state=65204, cost_of_attendance=88000, toefl_min=100, ielts_min=7.5,
         offers_intl_aid=True, intl_support_notes="Meets full need; need-aware for international applicants.",
         app_platforms=["common_app"], majors=[CS, ENG, BIO, BUS, ECON],
         deadlines={"early_decision": "11-01", "regular": "01-02", "transfer": "03-15"},
         supplemental_essay_count=1, application_fee=80),
    dict(name="New York University", city="New York", state="NY", control="private",
         undergrad_enrollment=29000, acceptance_rate=0.09, sat_25=1470, sat_75=1550,
         test_policy="optional", tuition_out_state=60438, cost_of_attendance=90000, toefl_min=100, ielts_min=7.5,
         offers_intl_aid=False, intl_support_notes="Most international undergraduates of any US university.",
         app_platforms=["common_app"], majors=[CS, BUS, ECON, PSY, BIO],
         deadlines={"early_decision": "11-01", "regular": "01-05", "transfer": "04-01"},
         supplemental_essay_count=1, application_fee=80),
    dict(name="Boston University", city="Boston", state="MA", control="private",
         undergrad_enrollment=18500, acceptance_rate=0.11, sat_25=1410, sat_75=1520,
         test_policy="optional", tuition_out_state=65168, cost_of_attendance=88000, toefl_min=90, ielts_min=7.0,
         offers_intl_aid=False, intl_support_notes="Merit scholarships open to international applicants.",
         app_platforms=["common_app"], majors=[CS, BUS, BIO, PSY, ECON],
         deadlines={"early_decision": "11-01", "regular": "01-06", "transfer": "03-15"},
         supplemental_essay_count=1, application_fee=80),
    dict(name="Northeastern University", city="Boston", state="MA", control="private",
         undergrad_enrollment=16000, acceptance_rate=0.06, sat_25=1440, sat_75=1540,
         test_policy="optional", tuition_out_state=63141, cost_of_attendance=85000, toefl_min=92, ielts_min=7.0,
         offers_intl_aid=False, intl_support_notes="Co-op program; many international pathway options.",
         app_platforms=["common_app"], majors=[CS, BUS, ENG, PSY],
         deadlines={"early_decision": "11-01", "early_action": "11-01", "regular": "01-01", "transfer": "04-01"},
         supplemental_essay_count=0, application_fee=75),
    dict(name="University of Southern California", city="Los Angeles", state="CA", control="private",
         undergrad_enrollment=21000, acceptance_rate=0.10, sat_25=1450, sat_75=1540,
         test_policy="optional", tuition_out_state=66640, cost_of_attendance=92000, toefl_min=100, ielts_min=7.0,
         offers_intl_aid=False, intl_support_notes="Merit aid open to international students; large intl community.",
         app_platforms=["common_app"], majors=[CS, BUS, ENG, PSY, ECON],
         deadlines={"early_action": "11-01", "regular": "01-15", "transfer": "02-15"},
         supplemental_essay_count=3, application_fee=85),
    dict(name="University of Florida", city="Gainesville", state="FL", control="public",
         undergrad_enrollment=34500, acceptance_rate=0.24, sat_25=1300, sat_75=1470, act_25=28, act_75=33,
         test_policy="required", tuition_in_state=6381, tuition_out_state=28659, cost_of_attendance=48000,
         toefl_min=80, ielts_min=6.0, offers_intl_aid=False,
         intl_support_notes="Very low in-state cost; limited intl aid.",
         app_platforms=["common_app", "institutional"], majors=[CS, BIO, BUS, PSY, NURS],
         deadlines={"regular": "11-01", "transfer": "05-01"}, supplemental_essay_count=1, application_fee=30),
    dict(name="Ohio State University", city="Columbus", state="OH", control="public",
         undergrad_enrollment=46000, acceptance_rate=0.51, sat_25=1260, sat_75=1450, act_25=27, act_75=32,
         test_policy="optional", tuition_in_state=12485, tuition_out_state=36722, cost_of_attendance=58000,
         toefl_min=79, ielts_min=6.5, offers_intl_aid=False,
         intl_support_notes="Big Ten school with broad program selection.",
         app_platforms=["common_app"], majors=[CS, ENG, BUS, BIO, PSY, NURS],
         deadlines={"early_action": "11-01", "regular": "02-01", "rolling": "rolling"},
         supplemental_essay_count=0, application_fee=60),
    dict(name="Pennsylvania State University", city="University Park", state="PA", control="public",
         undergrad_enrollment=41000, acceptance_rate=0.55, sat_25=1160, sat_75=1370,
         test_policy="optional", tuition_in_state=19672, tuition_out_state=38651, cost_of_attendance=60000,
         toefl_min=80, ielts_min=6.5, offers_intl_aid=False,
         intl_support_notes="Rolling admission after priority date.",
         app_platforms=["common_app", "institutional"], majors=[CS, ENG, BUS, PSY, BIO, NURS],
         deadlines={"early_action": "11-01", "regular": "12-01", "rolling": "rolling", "transfer": "04-01"},
         supplemental_essay_count=0, application_fee=65),
    dict(name="Arizona State University", city="Tempe", state="AZ", control="public",
         undergrad_enrollment=65000, acceptance_rate=0.90, sat_25=1120, sat_75=1360, act_25=21, act_75=29,
         test_policy="optional", tuition_in_state=12051, tuition_out_state=32193, cost_of_attendance=52000,
         toefl_min=61, ielts_min=6.0, offers_intl_aid=False,
         intl_support_notes="Very international-friendly; large merit scholarships for high stats.",
         app_platforms=["common_app", "institutional"], majors=[CS, ENG, BUS, PSY, BIO, NURS],
         deadlines={"rolling": "rolling", "regular": "02-01"}, supplemental_essay_count=0, application_fee=70),
    dict(name="University of Alabama", city="Tuscaloosa", state="AL", control="public",
         undergrad_enrollment=33000, acceptance_rate=0.80, sat_25=1070, sat_75=1330, act_25=23, act_75=31,
         test_policy="optional", tuition_in_state=11900, tuition_out_state=32300, cost_of_attendance=50000,
         toefl_min=71, ielts_min=6.0, offers_intl_aid=False,
         intl_support_notes="Generous automatic merit scholarships tied to GPA/test scores.",
         app_platforms=["common_app", "institutional"], majors=[BUS, NURS, PSY, BIO, ENG, CS],
         deadlines={"rolling": "rolling", "regular": "02-01"}, supplemental_essay_count=0, application_fee=40),
    dict(name="San Jose State University", city="San Jose", state="CA", control="public",
         undergrad_enrollment=27000, acceptance_rate=0.77, test_policy="blind",
         tuition_in_state=7852, tuition_out_state=19732, cost_of_attendance=42000, toefl_min=61, ielts_min=6.0,
         offers_intl_aid=False, intl_support_notes="Silicon Valley location; strong industry placement for CS.",
         app_platforms=["cal_state_apply"], majors=[CS, ENG, BUS, PSY, NURS],
         deadlines={"regular": "11-30", "transfer": "11-30"}, supplemental_essay_count=0, application_fee=70),
    dict(name="University of Wisconsin-Madison", city="Madison", state="WI", control="public",
         undergrad_enrollment=37000, acceptance_rate=0.43, sat_25=1350, sat_75=1500, act_25=28, act_75=33,
         test_policy="optional", tuition_in_state=11205, tuition_out_state=40603, cost_of_attendance=62000,
         toefl_min=80, ielts_min=6.5, offers_intl_aid=False,
         intl_support_notes="Strong research university; limited intl aid.",
         app_platforms=["common_app", "institutional"], majors=[CS, ENG, BIO, ECON, PSY],
         deadlines={"early_action": "11-01", "regular": "01-31", "transfer": "03-01"},
         supplemental_essay_count=1, application_fee=70),
]


def seed_universities(db: Session) -> int:
    """Insert sample universities if the table is empty. Returns rows added."""
    if db.query(University).count() > 0:
        return 0
    for row in SAMPLE_UNIVERSITIES:
        db.add(University(**row))
    db.commit()
    return len(SAMPLE_UNIVERSITIES)
